mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^$',views.blog_title,name='blog_title'),
	url(r'(?P<a_id>\d+)/$',views.article,name='blog_detail')
]

mysite/mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog',app_name='blog')),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User#User是django默认的，指的是创建的用户

# Create your models here.

class BlogArticles(models.Model):
	#字段和其属性
	title=models.CharField(max_length=30)
	author=models.ForeignKey(User,related_name="blog_posts")
	body=models.TextField()
	publish=models.DateTimeField(default=timezone.now)

	class Meta:
		#按照publish逆顺序显示
		ordering=('-publish',)

	def __str__(self):
		#为了在页面中不单调显示，而显示文章标题
		return self.title

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import BlogArticles

# Create your views here.
def blog_title(request):
	blogs=BlogArticles.objects.all()
	return render(request,"blog/titles.html",{"blogs":blogs})

def article(request,a_id):
	blog=get_object_or_404(BlogArticles,id=a_id)
	publish_time=blog.publish
	return render(request,"blog/article.html",{'blog':blog,'publish':publish_time})

mysite/blog/templates/base.html
<<!DOCTYPE html>
<html lang="zh-cn">
<head>
	<meta charset="UTF-8">
	<meta name="viewpoint" content="width=device-width,initial-scale=1">
	<title>{%block title%}{%endblock%}</title>
	<link rel="stylesheet" type="text/css" href="http://necolas.github.io/normalize.css/">
	<link rel="stylesheet" type="text/css" href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css">
</head>
<body>
	<div class="container">
		{%block content%}
		{%endblock%}
	</div>
	<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
	<script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

mysite/blog/templates/blog/article.html
{% extends "base.html" %}

{%block title%}blog article{%endblock%}

{%block content%}
<div class="row text-center vertical-middle-sm">
	<h1>{{blog}}</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-3">
		<h3>作者简介</h3>
		<p>JosonLee</p>
		<p>Python、大数据学习中。。。</p>
		<img src="https://s1.ax1x.com/2018/05/18/C6Tw9I.png" alt="C6Tw9I.png" width="200px" height="150px" border="0" />
	</div>
	<div class="col-xs-9 col-md-7">	
		<p class="text-center"><span>{{blog.author.username}}</span><span style="margin-left: 20px">{{publish}}</span></p>
		<div>{{blog.body}}</div>
</div>
	<div class="col-xs-2 col-md-2">
		<h2>广告</h2>
		<p><a target="_blank" href="https://www.baidu.com">百度一下:</a><a target="_blank" 	href="https://blog.csdn.net/lzw2016"><span>lzw2016</span></a> </p>
		<img src="https://tse4.mm.bing.net/th?id=OIP.9zkKGHtU0FkbjYXV7DL4bQHaFE&pid=Api" width="200px">
	</div>
</div>
{%endblock%}

mysite/blog/templates/blog/titles.html
{%extends "base.html"%}

{%block title%}blog title{%endblock%}

{%block content%}
<div class="row text-center vertical-middle-sm">	<h1>My Blog</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-8">
		<ul>
			{%for blog in blogs%}
				<li><a target="_blank" href="{%url 'blog:blog_detail' blog.id%}">{{blog.title}}</a></li>
			{%endfor%}
		</ul>
	</div>
	<div class="col-xs-6 col-md-4">
		<h2>广告</h2>
		<p>百度一下:<a target="_blank" 	href="https://blog.csdn.net/lzw2016"><span>lzw2016</span></a> </p>
		<img src="https://tse4.mm.bing.net/th?id=OIP.9zkKGHtU0FkbjYXV7DL4bQHaFE&pid=Api" width="200px">
	</div>
</div>

{%endblock%}